sudo: required
compiler: gcc
dist: xenial
language: c
cache: ccache

before_install:
  - sudo apt-get update -qq

jobs:
  include:
    - stage: Job1
      os: linux
      env: JOB="Job1"
      script: "./main.sh"
    - stage: Job2
      os: linux
      env: JOB="Job2"
      script: "./main.sh"
    - stage: UseJobs
      os: linux
      env: JOB="UseJobs"
      script: "./main.sh"
