sudo: required
compiler: gcc
dist: xenial
language: c

before_install:
  - sudo apt-get update -qq

jobs:
  include:
    - stage: Build 
      os: linux
      env: CACHE_NAME=shared
      script: "./job1.sh"
      cache:
         directories:
            - /home/travis/dist/
    - stage: Build
      os: linux
      env: CACHE_NAME=shared
      script: "./job2.sh"
      cache:
         directories:
            - /home/travis/dist/
    - stage: Deploy
      os: linux
      env: CACHE_NAME=shared
      script: "./deploy.sh"
      cache:
         directories:
            - /home/travis/dist/


