sudo: required
compiler: gcc
dist: xenial
language: c
cache:
   directories:
      - /home/travis/dist/

before_install:
  - sudo apt-get update -qq

jobs:
  include:
    - stage: Build 
      os: linux
      script: "./job1.sh"
    - stage: Build
      os: linux
      script: "./job2.sh"
    - stage: Build
      os: linux
      script: "./deploy.sh"
